
#It's recommended to edit the config BEFORE you make/play a world. While editing the config in an already generated world can work sometimes, there may be visual bugs or just bugs in general.
#This category holds general values that will mostly be customized by most.
["Starting Configurations"]
	#This is how many lives you'll start out with in the world.
	#Range: > 1
	"Starting Lives:" = 3
	#This is how many lives you'll lose every death.
	#Range: > 1
	"Amount of Lives Lost Per Death:" = 1
	#This value determines whether you get banned or go into spectator mode when you lose all your lives.
	"Banned Upon Dying:" = false

